version: 0.2

env:
  # 1. Ensure the fallback or primary name variable is declared
  variables:
    # This must match the exact key passed down by your CodePipeline/GitHub Actions environment env context
    SECRET_NAME_VAR: "rds!db-6c4a6398-7b05-4750-b0ff-395702773b38" 
    CONFIG_BUCKET_NAME: "rmvpapz-research-watcher"
  # 2. Reference the variable string directly inside the key resolution block
  secrets:
    MY_DATABASE_PASSWORD: "$SECRET_NAME_VAR:password"

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Installing uv..."
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.local/bin:$PATH"
      - yum install -y zip
    finally:
      - echo Install and docker login stage over
  pre_build:
    commands:
      - mkdir -p lambda_package
  build:
    commands:
      - echo "Creating a pristine isolated virtual environment..."
      - uv venv .lambda_venv
      - source .lambda_venv/bin/activate
      - uv sync --frozen --no-dev --active
      - echo "Extracting runtime libraries to deployment folder..."
      # Copying out of site-packages preserves pure binary runtimes for Lambda
      - cp -R .lambda_venv/lib/python3.13/site-packages/* ./lambda_package/

      - echo "Injecting application code modules..."
      - cp -R src/api ./lambda_package/
      - cp -R src/shared ./lambda_package/
      - echo "Fetching environment file from S3..."
      - aws s3 cp "s3://$CONFIG_BUCKET_NAME/scraper-aws.env" ./lambda_package/.env
      - echo "" >> ./lambda_package/.env
      - echo "POSTGRES_PASSWORD=${MY_DATABASE_PASSWORD}" >> ./lambda_package/.env
    finally:
      - echo lambda package ready

  post_build:
    commands:
      - echo "Letting CodeBuild handle the artifact bundling of lambda_package"

artifacts:
  files:
    - "**/*"
  base-directory: lambda_package
  discard-paths: no
