# 1. Use the official uv image to get the binary
FROM ghcr.io/astral-sh/uv:latest AS uv

# 2. Use a standard Python image for your app
#FROM python:3.13-slim
FROM public.ecr.aws/docker/library/python:3.13-slim

# 3. Copy the uv binary from the uv image
COPY --from=uv /uv /bin/uv

ENV UV_SYSTEM_PYTHON=1
ENV UV_PYTHON_DOWNLOADS=never

WORKDIR /app

# Copy the whole project so shared/ is available
COPY pyproject.toml uv.lock ./ 

RUN uv sync --frozen --no-cache --no-install-project

COPY  . .
RUN uv sync --frozen --no-cache

CMD ["uv","run","python", "-m", "scraper.main"]